// Convert data/vocabulary/awl.json (570 Coxhead AWL headwords + Wiktionary
// definitions) into a TypeScript module the app imports.

import { readFile, writeFile } from "node:fs/promises";

const SRC = new URL("../data/vocabulary/awl.json", import.meta.url);
const OUT = new URL("../data/vocabulary/awl.ts", import.meta.url);

const data = JSON.parse(await readFile(SRC, "utf-8"));

function tsString(s) {
  return "`" + String(s).replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";
}

let out = `// AUTO-GENERATED by scripts/emit-awl-ts.mjs — do not edit by hand.
//
// Source 1: Academic Word List (AWL) — Coxhead, A. (2000), "A New Academic
//           Word List", TESOL Quarterly 34(2): 213-238. Headword list reused
//           with attribution (factual word-frequency data is not copyrightable).
//           https://www.wgtn.ac.nz/lals/resources/academicwordlist
//
// Source 2: Definitions and example sentences from English Wiktionary,
//           licensed CC-BY-SA 4.0. https://en.wiktionary.org/

export interface AwlWord {
  word: string;
  /** Coxhead 2000 sublist (1 = most frequent, 10 = least frequent). */
  sublist: number;
  partOfSpeech: string;
  definition: string;
  /** May be empty if Wiktionary did not supply a citation. */
  example: string;
}

export const AWL_WORDS: AwlWord[] = [
`;

const sorted = data
  .filter((d) => !d.missing)
  .slice()
  .sort((a, b) => a.sublist - b.sublist || a.word.localeCompare(b.word));

for (const d of sorted) {
  out += "  {\n";
  out += `    word: ${tsString(d.word)},\n`;
  out += `    sublist: ${d.sublist},\n`;
  out += `    partOfSpeech: ${tsString(d.partOfSpeech)},\n`;
  out += `    definition: ${tsString(d.definition)},\n`;
  out += `    example: ${tsString(d.example || "")},\n`;
  out += "  },\n";
}
out += "];\n";

await writeFile(OUT, out, "utf-8");
console.log(`Wrote ${sorted.length} AWL words → ${OUT.pathname}`);
